// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * @param {string} notificationId - This field is required.
 * @returns {boolean}
 */
function CancelScheduledNotification(notificationId) {
	// BEGIN USER CODE
    const firebase = require("react-native-firebase");
    if (!notificationId) {
        throw new TypeError("Input parameter 'Notification id' is required");
    }
    firebase.notifications().cancelNotification(notificationId);
    return true;
	// END USER CODE
}