// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * This gets a push notification registration token, which can be used to register this device in the push notifications module.
 * @returns {string}
 */
function GetPushNotificationToken() {
	// BEGIN USER CODE
    // Documentation https://rnfirebase.io/docs/v5.x.x/messaging/reference/Messaging#getToken
    const firebase = require("react-native-firebase");
    return firebase.messaging().getToken();
	// END USER CODE
}