// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * @returns {boolean}
 */
function HideKeyboard() {
	// BEGIN USER CODE
    // Documentation https://facebook.github.io/react-native/docs/keyboard
    const Keyboard = require("react-native").Keyboard;
    Keyboard.dismiss();
    return true;
	// END USER CODE
}