// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * @returns {boolean}
 */
function IsBiometricAuthenticationSupported() {
	// BEGIN USER CODE
    // Documentation https://github.com/naoufal/react-native-touch-id
    const TouchID = require("react-native-touch-id").default;
    return TouchID.isSupported()
        .then(() => true)
        .catch(() => false);
	// END USER CODE
}