// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * @returns {boolean}
 */
function IsWifiConnection() {
	// BEGIN USER CODE
    const NetInfo = require("react-native").NetInfo;
    return NetInfo.getConnectionInfo().then(({ type }) => type === "wifi");
	// END USER CODE
}