// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * @param {string} message - The message to share. This field is required.
 * @param {string} title - Title of the message to share. Only some share targets use this value.
 * @returns {boolean}
 */
function Share(message, title) {
	// BEGIN USER CODE
    // Documentation https://facebook.github.io/react-native/docs/share
    const RNShare = require("react-native").Share;
    if (!message) {
        throw new TypeError("Input parameter 'Message' is required");
    }
    return RNShare.share({ message, title }).then(result => {
        if (result.action === RNShare.dismissedAction) {
            return false;
        }
        return true;
    });
	// END USER CODE
}