// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * @param {Big} timeToSleep
 * @returns {boolean}
 */
function JavaScript_Sleep(timeToSleep) {
	// BEGIN USER CODE
	const sleep = (milliseconds) => {
		return new Promise(resolve => setTimeout(resolve, milliseconds))
	}

	return sleep(timeToSleep);
	// END USER CODE
}