// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package serverselftest.actions;

import com.mendix.core.Core;
import com.mendix.externalinterface.connector.RequestHandler;
import com.mendix.m2ee.api.IMxRuntimeRequest;
import com.mendix.m2ee.api.IMxRuntimeResponse;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class EnableHandlers extends CustomJavaAction<java.lang.Boolean>
{
	public EnableHandlers(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		if( _handlerSSO == null ) {
			_handlerSSO = new Handler("SSO");
			Core.addRequestHandler("sso/", _handlerSSO);
			Core.addRequestHandler("SSO/", _handlerSSO);
			
			_handlerDeeplink = new Handler("Deeplink");
			Core.addRequestHandler("link/", _handlerDeeplink);
			_handlerOpenId = new Handler("OpenID");
			Core.addRequestHandler("openid/", _handlerOpenId);
		}
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "EnableHandlers";
	}

	// BEGIN EXTRA CODE
	
	private static Handler _handlerSSO = null;
	private static Handler _handlerDeeplink = null;
	private static Handler _handlerOpenId = null;
	
	private static class Handler extends RequestHandler {
		private String name;
		public Handler(String name) {
			this.name = name;
		}
		@Override
		protected void processRequest(IMxRuntimeRequest req, IMxRuntimeResponse resp, String params) throws Exception {
			resp.setStatus(200);
			resp.getWriter().append("Hello " + this.name + " World");
		}
	}
	
	// END EXTRA CODE
}
