// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package serverselftest.actions;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

public class GetFileContent extends CustomJavaAction<java.lang.Boolean>
{
	/** @deprecated use FileObject.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __FileObject;
	private final system.proxies.FileDocument FileObject;

	public GetFileContent(
		IContext context,
		IMendixObject _fileObject
	)
	{
		super(context);
		this.__FileObject = _fileObject;
		this.FileObject = _fileObject == null ? null : system.proxies.FileDocument.initialize(getContext(), _fileObject);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		InputStream inputStream = Core.getFileDocumentContent(getContext(), __FileObject);
        BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
        StringBuilder out = new StringBuilder();
        String line;
        while ((line = reader.readLine()) != null) {
            out.append(line);
        }
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetFileContent";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
