// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package serverselftest.actions;

import com.mendix.core.Core;
import com.mendix.core.conf.Configuration.ScheduledEventExecution;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import serverselftest.proxies.InstanceDetails;

public class GetInstanceInfo extends CustomJavaAction<java.lang.Boolean>
{
	public GetInstanceInfo(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		IMendixObject instanceObj = Core.instantiate(getContext(), InstanceDetails.entityName);
		instanceObj.setValue(getContext(), InstanceDetails.MemberNames.InstanceId.toString(), Core.getXASId());
		Runtime rt = Runtime.getRuntime();
		long maxMem = rt.maxMemory();
		if( maxMem != Long.MAX_VALUE ) {
			maxMem = (maxMem / 1048576L);
			instanceObj.setValue(getContext(), InstanceDetails.MemberNames.JVMMaxMemory.toString(), maxMem + " MB");
		}
		else 
			instanceObj.setValue(getContext(), InstanceDetails.MemberNames.JVMMaxMemory.toString(), "(not set)" );
		instanceObj.setValue(getContext(), InstanceDetails.MemberNames.JVMAvailableProcessors.toString(), rt.availableProcessors());
		
		
		instanceObj.setValue(getContext(), InstanceDetails.MemberNames.ScheduledEventExecution.toString(), Core.getConfiguration().getScheduledEventExecution().toString());
		instanceObj.setValue(getContext(), InstanceDetails.MemberNames.IsLocalFileSystemCleaningEnabled.toString(), Core.getConfiguration().isLocalFileSystemCleaningEnabled());
		
		Core.commit(getContext(), instanceObj);
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetInstanceInfo";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
